import { Creator, SocialAccount, Post, BrandDeal, Benchmark, BrandDirectoryItem } from './types';

export const MOCK_CREATORS: Creator[] = [
  {
    id: 'creator-ananya',
    email: 'ananya@creators.co',
    full_name: 'Ananya Verma',
    niche: 'Fashion',
    subscription_tier: 'pro',
    currency: 'USD',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
    bio: 'Sustainable minimalist fashion, luxury dupes & conscious styling.',
    monthly_revenue: 1850,
    revenue_target: 3000,
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'creator-aarav',
    email: 'aarav@techpulse.io',
    full_name: 'Aarav Patel',
    niche: 'Tech',
    subscription_tier: 'free',
    currency: 'USD',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    bio: 'Productivity setups, developer tools & AI workflow breakdowns.',
    monthly_revenue: 0,
    revenue_target: 2000,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'creator-meera',
    email: 'meera@glowlifestyle.com',
    full_name: 'Meera Iyer',
    niche: 'Lifestyle',
    subscription_tier: 'pro',
    currency: 'USD',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=256&q=80',
    bio: 'Skincare routines, wellness rituals & urban lifestyle aesthetics.',
    monthly_revenue: 950,
    revenue_target: 4000,
    created_at: '2025-11-10T00:00:00Z',
  },
];

export const MOCK_SOCIAL_ACCOUNTS: Record<string, SocialAccount[]> = {
  'creator-ananya': [
    {
      id: 'soc-ananya-ig',
      creator_id: 'creator-ananya',
      platform: 'instagram',
      handle: '@AnanyaStyle',
      follower_count: 28400,
      avg_engagement_rate: 2.4,
      last_synced_at: '12 minutes ago',
      connected: true,
    },
    {
      id: 'soc-ananya-tt',
      creator_id: 'creator-ananya',
      platform: 'tiktok',
      handle: '@ananyastyle',
      follower_count: 14200,
      avg_engagement_rate: 3.1,
      last_synced_at: '12 minutes ago',
      connected: true,
    },
    {
      id: 'soc-ananya-yt',
      creator_id: 'creator-ananya',
      platform: 'youtube',
      handle: 'Ananya Verma Studio',
      follower_count: 8500,
      avg_engagement_rate: 4.8,
      last_synced_at: '12 minutes ago',
      connected: false,
    },
  ],
  'creator-aarav': [
    {
      id: 'soc-aarav-ig',
      creator_id: 'creator-aarav',
      platform: 'instagram',
      handle: '@aaravtech',
      follower_count: 18000,
      avg_engagement_rate: 3.4,
      last_synced_at: '1 hour ago',
      connected: true,
    },
    {
      id: 'soc-aarav-yt',
      creator_id: 'creator-aarav',
      platform: 'youtube',
      handle: 'Aarav Tech Lab',
      follower_count: 12500,
      avg_engagement_rate: 5.2,
      last_synced_at: '1 hour ago',
      connected: true,
    },
  ],
  'creator-meera': [
    {
      id: 'soc-meera-ig',
      creator_id: 'creator-meera',
      platform: 'instagram',
      handle: '@meera.glow',
      follower_count: 85000,
      avg_engagement_rate: 0.22, // Low ER anomaly! 0.22% vs 1.2% benchmark
      last_synced_at: '30 minutes ago',
      connected: true,
    },
    {
      id: 'soc-meera-tt',
      creator_id: 'creator-meera',
      platform: 'tiktok',
      handle: '@meeraglow',
      follower_count: 42000,
      avg_engagement_rate: 0.35,
      last_synced_at: '30 minutes ago',
      connected: true,
    },
  ],
};

export const MOCK_POSTS: Record<string, Post[]> = {
  'creator-ananya': [
    {
      id: 'post-ananya-1',
      creator_id: 'creator-ananya',
      platform: 'instagram',
      post_url: 'https://instagram.com/p/DF9382',
      title: '5 Autumn Capsule Wardrobe Essentials on a Budget',
      format: 'reel',
      views_count: 42300,
      engagement_rate: 3.8,
      retention_rate: 68.4,
      status: 'optimal',
      likes: 2140,
      comments: 184,
      shares: 420,
      saves: 890,
      duration_s: 34,
      hook_dropoff_pct: 18.2,
      caption: 'The secret to quiet luxury without spending thousands: timeless neutral tailoring. Which piece would you style first? ✨',
      hashtags: ['#capsulewardrobe', '#autumnfashion', '#smartluxury', '#minimalstyle'],
      published_at: '2026-10-04T18:30:00Z',
      thumbnail_url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=400&q=80',
      retention_curve: [
        { second: 0, retentionPct: 100 },
        { second: 3, retentionPct: 88 },
        { second: 10, retentionPct: 76 },
        { second: 20, retentionPct: 69 },
        { second: 34, retentionPct: 62 },
      ],
    },
    {
      id: 'post-ananya-2',
      creator_id: 'creator-ananya',
      platform: 'instagram',
      post_url: 'https://instagram.com/p/DF8711',
      title: 'Late Night Q&A & Styling Chat',
      format: 'reel',
      views_count: 6400,
      engagement_rate: 1.1,
      retention_rate: 22.0,
      status: 'need_audit',
      likes: 210,
      comments: 18,
      shares: 12,
      saves: 34,
      duration_s: 78,
      hook_dropoff_pct: 54.0,
      caption: 'Quick late night stream recap answering your weekend fashion dilemmas! #styling',
      hashtags: ['#fashionqna', '#casualchat'],
      published_at: '2026-10-02T23:45:00Z', // 11:45 PM - bad hour outlier!
      thumbnail_url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=400&q=80',
      retention_curve: [
        { second: 0, retentionPct: 100 },
        { second: 3, retentionPct: 46 }, // 54% drop at hook!
        { second: 15, retentionPct: 30 },
        { second: 30, retentionPct: 24 },
        { second: 78, retentionPct: 18 },
      ],
    },
    {
      id: 'post-ananya-3',
      creator_id: 'creator-ananya',
      platform: 'instagram',
      post_url: 'https://instagram.com/p/DF7622',
      title: 'ZARA Trench Coat vs High-End Designer Blind Test',
      format: 'reel',
      views_count: 36800,
      engagement_rate: 2.9,
      retention_rate: 59.0,
      status: 'optimal',
      likes: 1820,
      comments: 215,
      shares: 310,
      saves: 620,
      duration_s: 42,
      hook_dropoff_pct: 22.5,
      caption: 'Can you spot the $90 vs $1,200 trench coat? The fabric weight will shock you! #dupes',
      hashtags: ['#zarahaul', '#designerdupes', '#fashionreview'],
      published_at: '2026-09-29T19:00:00Z',
      thumbnail_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=400&q=80',
      retention_curve: [
        { second: 0, retentionPct: 100 },
        { second: 3, retentionPct: 82 },
        { second: 15, retentionPct: 70 },
        { second: 30, retentionPct: 62 },
        { second: 42, retentionPct: 56 },
      ],
    },
    {
      id: 'post-ananya-4',
      creator_id: 'creator-ananya',
      platform: 'instagram',
      post_url: 'https://instagram.com/p/DF6531',
      title: 'Neutral Color Harmony Cheat Sheet',
      format: 'carousel',
      views_count: 19400,
      engagement_rate: 2.4, // Right on par with baseline!
      retention_rate: 48.0,
      status: 'optimal',
      likes: 820,
      comments: 65,
      shares: 110,
      saves: 490,
      duration_s: 0,
      hook_dropoff_pct: 28.0,
      caption: 'Save this guide for the next time you stare at your closet thinking nothing matches! 🤍',
      hashtags: ['#colorpalette', '#stylingtips', '#outfitoftheday'],
      published_at: '2026-09-25T18:00:00Z',
      thumbnail_url: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=400&q=80',
    },
    {
      id: 'post-ananya-5',
      creator_id: 'creator-ananya',
      platform: 'instagram',
      post_url: 'https://instagram.com/p/DF5210',
      title: 'Sunday Morning Coffee & Outfit Prep',
      format: 'reel',
      views_count: 14200,
      engagement_rate: 2.3, // Ambiguous post - test case for Guardrail G1 "No Clear Cause"!
      retention_rate: 46.0,
      status: 'optimal',
      likes: 620,
      comments: 42,
      shares: 38,
      saves: 180,
      duration_s: 30,
      hook_dropoff_pct: 26.0,
      caption: 'Slow Sunday aesthetic ✨ What is your favorite ritual before the week starts?',
      hashtags: ['#sundayreset', '#aesthetic', '#coffeetime'],
      published_at: '2026-09-22T17:30:00Z',
      thumbnail_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=400&q=80',
      retention_curve: [
        { second: 0, retentionPct: 100 },
        { second: 3, retentionPct: 79 },
        { second: 15, retentionPct: 55 },
        { second: 30, retentionPct: 44 },
      ],
    },
  ],
  'creator-aarav': [
    {
      id: 'post-aarav-1',
      creator_id: 'creator-aarav',
      platform: 'instagram',
      post_url: 'https://instagram.com/p/TG1101',
      title: 'Top 3 Terminal Tools Every Developer Needs in 2026',
      format: 'reel',
      views_count: 32400,
      engagement_rate: 4.2,
      retention_rate: 72.0,
      status: 'optimal',
      likes: 1890,
      comments: 142,
      shares: 512,
      saves: 980,
      duration_s: 40,
      hook_dropoff_pct: 14.0,
      caption: 'Stop using default bash. These 3 CLI tools will 10x your productivity! #devtools',
      hashtags: ['#developer', '#coding', '#terminal', '#productivity'],
      published_at: '2026-10-03T17:00:00Z',
      thumbnail_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=400&q=80',
    },
  ],
  'creator-meera': [
    {
      id: 'post-meera-1',
      creator_id: 'creator-meera',
      platform: 'instagram',
      post_url: 'https://instagram.com/p/ME9901',
      title: 'Morning Glass Skin Routine (Ceramides + Niacinamide)',
      format: 'reel',
      views_count: 20100, // Typical plays ~20k plays despite 85k followers!
      engagement_rate: 0.22, // 0.22% low engagement anomaly!
      retention_rate: 28.0,
      status: 'need_audit',
      likes: 135,
      comments: 18,
      shares: 12,
      saves: 45,
      duration_s: 48,
      hook_dropoff_pct: 48.0,
      caption: 'Layering hydration step-by-step for dewy skin all day! Drop your favorite serum below.',
      hashtags: ['#skincareroutine', '#glassskin', '#wellness'],
      published_at: '2026-10-01T23:30:00Z',
      thumbnail_url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80',
      retention_curve: [
        { second: 0, retentionPct: 100 },
        { second: 3, retentionPct: 52 },
        { second: 15, retentionPct: 35 },
        { second: 30, retentionPct: 28 },
        { second: 48, retentionPct: 22 },
      ],
    },
  ],
};

export const MOCK_BRAND_DEALS: BrandDeal[] = [
  {
    id: 'deal-1',
    creator_id: 'creator-ananya',
    brand_name: 'Glossier',
    brand_category: 'Beauty',
    brand_logo_url: 'https://avatar.vercel.sh/glossier.svg?text=GL',
    deliverables: { reels: 1, tiktoks: 1, stories: 2, youtube_integrations: 0 },
    quoted_rate: 850,
    ai_suggested_rate: 920,
    status: 'accepted',
    stage: 'won',
    ftc_compliant: true,
    usage_rights: '30_day_ads',
    notes: 'Contract signed. Campaign goes live on 18th Oct.',
    created_at: '2026-09-28T10:00:00Z',
  },
  {
    id: 'deal-2',
    creator_id: 'creator-ananya',
    brand_name: 'Casetify',
    brand_category: 'Tech',
    brand_logo_url: 'https://avatar.vercel.sh/casetify.svg?text=CS',
    deliverables: { reels: 1, tiktoks: 0, stories: 3, youtube_integrations: 0 },
    quoted_rate: 650,
    ai_suggested_rate: 680,
    status: 'pitching',
    stage: 'negotiating',
    ftc_compliant: true,
    usage_rights: 'organic',
    notes: 'Brand offered $450 initially. Counter-offered with $650 using Pricer rationale.',
    created_at: '2026-10-02T14:20:00Z',
  },
  {
    id: 'deal-3',
    creator_id: 'creator-ananya',
    brand_name: 'Reformation',
    brand_category: 'Fashion',
    brand_logo_url: 'https://avatar.vercel.sh/reformation.svg?text=RF',
    deliverables: { reels: 2, tiktoks: 0, stories: 4, youtube_integrations: 0 },
    quoted_rate: 1400,
    ai_suggested_rate: 1450,
    status: 'pitching',
    stage: 'pitched',
    ftc_compliant: true,
    usage_rights: 'organic',
    notes: 'Cold pitch drafted with Crest AI. Awaiting reply.',
    created_at: '2026-10-05T09:15:00Z',
  },
  {
    id: 'deal-4',
    creator_id: 'creator-ananya',
    brand_name: 'Mejuri',
    brand_category: 'Fashion',
    brand_logo_url: 'https://avatar.vercel.sh/mejuri.svg?text=MJ',
    deliverables: { reels: 1, tiktoks: 0, stories: 1, youtube_integrations: 0 },
    quoted_rate: 550,
    ai_suggested_rate: 550,
    status: 'accepted',
    stage: 'paid',
    ftc_compliant: true,
    usage_rights: 'organic',
    notes: 'Invoice #CR-2026-08 settled via Stripe ($550).',
    created_at: '2026-09-10T11:00:00Z',
  },
];

export const MOCK_BENCHMARKS: Benchmark[] = [
  { platform: 'instagram', niche: 'Fashion', follower_tier: 'micro', median_er: 2.0, cpm_low: 20, cpm_mid: 28, cpm_high: 35 },
  { platform: 'instagram', niche: 'Tech', follower_tier: 'micro', median_er: 2.2, cpm_low: 25, cpm_mid: 32, cpm_high: 45 },
  { platform: 'instagram', niche: 'Lifestyle', follower_tier: 'mid', median_er: 1.2, cpm_low: 12, cpm_mid: 18, cpm_high: 25 },
  { platform: 'instagram', niche: 'Beauty', follower_tier: 'micro', median_er: 2.1, cpm_low: 22, cpm_mid: 30, cpm_high: 40 },
  { platform: 'instagram', niche: 'Fitness', follower_tier: 'micro', median_er: 2.3, cpm_low: 18, cpm_mid: 26, cpm_high: 36 },
];

export const MOCK_BRAND_DIRECTORY: BrandDirectoryItem[] = [
  {
    id: 'b-1',
    name: 'Gymshark',
    category: 'Fitness',
    typical_budget_tier: '$1,500 – $4,000',
    min_budget: 1500,
    max_budget: 4000,
    preferred_platforms: ['instagram', 'tiktok'],
    contact_email: 'partnerships@gymshark.com',
    logo_url: 'https://avatar.vercel.sh/gymshark.svg?text=GS',
    description: 'Activewear giant prioritizing high-energy workout reels and transformation stories.',
  },
  {
    id: 'b-2',
    name: 'Notion',
    category: 'Tech',
    typical_budget_tier: '$1,000 – $3,500',
    min_budget: 1000,
    max_budget: 3500,
    preferred_platforms: ['youtube', 'instagram', 'tiktok'],
    contact_email: 'creators@notion.so',
    logo_url: 'https://avatar.vercel.sh/notion.svg?text=NO',
    description: 'All-in-one productivity workspace actively commissioning setup tours & template showcases.',
  },
  {
    id: 'b-3',
    name: 'Glossier',
    category: 'Beauty',
    typical_budget_tier: '$800 – $2,500',
    min_budget: 800,
    max_budget: 2500,
    preferred_platforms: ['instagram', 'tiktok'],
    contact_email: 'collabs@glossier.com',
    logo_url: 'https://avatar.vercel.sh/glossier.svg?text=GL',
    description: 'Skincare and beauty pioneer famous for natural, authentic no-makeup looks.',
  },
  {
    id: 'b-4',
    name: 'Casetify',
    category: 'Tech',
    typical_budget_tier: '$500 – $2,000',
    min_budget: 500,
    max_budget: 2000,
    preferred_platforms: ['instagram', 'tiktok', 'youtube'],
    contact_email: 'influencers@casetify.com',
    logo_url: 'https://avatar.vercel.sh/casetify.svg?text=CS',
    description: 'Global tech accessories brand seeking aesthetic unboxings and daily carry styling.',
  },
  {
    id: 'b-5',
    name: 'Athletic Greens (AG1)',
    category: 'Lifestyle',
    typical_budget_tier: '$2,000 – $6,000',
    min_budget: 2000,
    max_budget: 6000,
    preferred_platforms: ['youtube', 'instagram'],
    contact_email: 'creators@athleticgreens.com',
    logo_url: 'https://avatar.vercel.sh/ag1.svg?text=AG',
    description: 'Daily foundational nutrition supplement sponsoring routine & wellness morning videos.',
  },
  {
    id: 'b-6',
    name: 'Reformation',
    category: 'Fashion',
    typical_budget_tier: '$1,200 – $3,500',
    min_budget: 1200,
    max_budget: 3500,
    preferred_platforms: ['instagram', 'tiktok'],
    contact_email: 'vip@thereformation.com',
    logo_url: 'https://avatar.vercel.sh/reformation.svg?text=RF',
    description: 'Sustainable women’s clothing line focusing on timeless dresses and eco-friendly silhouettes.',
  },
  {
    id: 'b-7',
    name: 'Raycon',
    category: 'Tech',
    typical_budget_tier: '$600 – $1,800',
    min_budget: 600,
    max_budget: 1800,
    preferred_platforms: ['youtube', 'tiktok'],
    contact_email: 'affiliates@rayconglobal.com',
    logo_url: 'https://avatar.vercel.sh/raycon.svg?text=RY',
    description: 'Wireless earbuds and audio devices looking for everyday lifestyle sound tests.',
  },
  {
    id: 'b-8',
    name: 'Alo Yoga',
    category: 'Fitness',
    typical_budget_tier: '$1,500 – $5,000',
    min_budget: 1500,
    max_budget: 5000,
    preferred_platforms: ['instagram', 'tiktok'],
    contact_email: 'influencers@aloyoga.com',
    logo_url: 'https://avatar.vercel.sh/alo.svg?text=AY',
    description: 'Mindful movement and studio-to-street yoga apparel brand.',
  },
];
